# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: All Geekness Great and Small
url: http://dancrumb.com
email: dancrumb@gmail.com
description: Dan Rumney's personal blog
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  dancrumb
timezone: America/Chicago

# Build settings
markdown: kramdown
kramdown:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
  math_engine: katex


exclude:
  - vendor

defaults:
  -
    scope:
      type: posts
    values:
      author:
        email: dancrumb@gmail.com
        display_name: Dan Rumney
        first_name: 'Dan'
        last_name: 'Rumney'

theme: jekyll-theme-hacker